config/urls.py
from django.contrib import admin
from django.urls import path, include

# print("config입니")

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),

]

polls/urls.py
from django.urls import path

from .views import index, detail, results, vote, IndexView, DetailView, ResultsView

app_name = 'polls'

# print("polls입니다")


urlpatterns = [
    path('', index, name='index'),
    path('<int:question_id>/', detail, name='detail'),
    path('<int:question_id>/results/', results, name='results'),
    path('<int:question_id>/vote/', vote, name='vote'),

    path('cbv/', IndexView.as_view(), name='cbv-index'),
    path('cbv/<int:pk>/', DetailView.as_view(), name='cbv-detail'),
    path('cbv/<int:pk>/', ResultsView.as_view(), name='cbv-detail')
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone


# Create your models here.


class Question(models.Model):

    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.http import HttpResponse, Http404
# Create your views here.
from django.shortcuts import render, get_object_or_404, redirect
from django.template import loader

from polls.models import Question, Choice


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    output = ", ".join([q.question_text for q in latest_question_list])
    template = loader.get_template('polls/index.html')
    context = {
        'latest_question_list': latest_question_list
    }
    return HttpResponse(template.render(context, request))


def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    # == question = get_object_or_404(Question, pk = question_id)

    context = {
        'question': question,
    }
    # return HttpResponse(f"You're looking at question {question_id}.")
    return render(request, 'polls/detail.html', context)


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    # choices = question.choice_set.all()
    context = {'question': question}
    return render(request, 'polls/results.html', context)
    # response = "you're looking at the results of question {}"
    # return HttpResponse(response.format(question_id))


def vote(request, question_id):
    # 특정 Question에 해당하는
    # 특정 Choice의 votes를 1 늘리기

    # 이후 특정 Question에 해당하는 results 페이지로 이동
    if request.method == 'POST':
        # GET으로 전달된 question_id에 해당하는 Question객체
        question = get_object_or_404(Question, pk=question_id)
        choice_pk = request.POST['choice']
        choice = get_object_or_404(Choice, pk=choice_pk)
        choice.votes += 1
        choice.save()
        return redirect('polls:results', question_id=question_id)

    # return HttpResponse(f"You're voting on question {question_id}")

polls/views/cbv.py
from django.views import generic, View

from ..models import Question


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.order_by("-pub_date")[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


class VoteView(View):
    def post(self, request, question_id):
        #post에 대한 요청만 받는
        pass

polls/views/fbv.py
from django.http import HttpResponse, Http404
# Create your views here.
from django.shortcuts import render, get_object_or_404, redirect
from django.template import loader
from django.utils.datastructures import MultiValueDictKeyError

from ..models import Question, Choice


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    output = ", ".join([q.question_text for q in latest_question_list])
    context = {
        'latest_question_list': latest_question_list
    }
    template = loader.get_template('polls/index.html')
    return HttpResponse(template.render(context, request))


def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    # == question = get_object_or_404(Question, pk = question_id)

    context = {
        'question': question,
    }
    # return HttpResponse(f"You're looking at question {question_id}.")
    return render(request, 'polls/detail.html', context)


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    # choices = question.choice_set.all()
    context = {'question': question}
    return render(request, 'polls/results.html', context)
    # response = "you're looking at the results of question {}"
    # return HttpResponse(response.format(question_id))


def vote(request, question_id):
    # 특정 Question에 해당하는
    # 특정 Choice의 votes를 1 늘리기

    # 이후 특정 Question에 해당하는 results 페이지로 이동
    if request.method == 'POST':

        # GET으로 전달된 question_id에 해당하는 Question객체
        try:
            question = get_object_or_404(Question, pk=question_id)
            choice_pk = request.POST['choice']
        except MultiValueDictKeyError:
            return redirect('polls:detail', question_id=question_id)

        choice = get_object_or_404(Choice, pk=choice_pk)
        choice.votes += 1
        choice.save()
        return redirect('polls:results', question_id=question_id)
    # return HttpResponse(f"You're voting on question {question_id}")

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>
{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}
<form action="{% url 'polls:vote' question_id=question.pk %}" method="POST">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice-{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice-{{ forloop.counter }}">{{ choice.choice_text }}</label>
        <br>
    {% endfor %}
    <button type="submit">Vote</button>
</form>

polls/templates/polls/index.html
{% if latest_question_list %}
<ul>
    {% for question in latest_question_list %}
        <li>
            <a href="{% url 'polls:detail' question_id=question.pk %}">
                {{ question.question_text }}
            </a>
        </li>

    {% endfor %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<ul>
<h1>{{ question.question_text }}</h1>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} : {{ choice.votes }}</li>
    {% endfor %}

    <a href="{% url 'polls:index' %}">돌아가기</a>
    <a href="{% url 'polls:detail' question_id=question.pk %}">다시 투표하기</a>
</ul>
</body>
</html>